apiVersion: v1
kind: ReplicationController
metadata:
   name: myjavaapp-rc
spec:
    replicas: 2
    selector:
       app: myjavaapp
       version: 2.6.4

    template:
      metadata:
         labels:
            app: myjavaapp
            version: 2.6.4

      spec:
        containers:
        - name: myjavacontainer
          image: satya578/myjavaapp:1
          ports:
          - containerPort: 8080
  